version: '3.3'
services:
  webapp:
    build: .
    container_name: 'webapp'
    ports:
      - 8001:8000
    environment:
      - background=purple
      - color=yellow
      - text=Hello world
      - PYTHONUNBUFFERED=1

