apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
  namespace: "{{ $.Values.metadata.namespace }}"
  labels:
    app.kubernetes.io/name: {{ $.Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Values.name }}
      app.kubernetes.io/instance: {{ $.Values.name }}
  strategy:
    type: RollingUpdate
  replicas: {{ $.Values.replica }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Values.name }}
        helm.sh/chart: wordpress-12.1.23
        app.kubernetes.io/instance: {{ $.Values.name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: {{ $.Values.name }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: "IfNotPresent"
#          env: {{ $.Values.env }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}

