apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host({{ .Values.ingress.host | quote }})
    kind: Rule
    services:
      - name: {{ $.Values.name }}
        namespace: {{ .Values.metadata.namespace }}
        port: {{ .Values.service.port }}
  tls:
    secretName: swapp-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-http
  namespace: {{ .Values.metadata.namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host({{ .Values.ingress.host | quote }})
    middlewares:
      - name: redirect-https
    kind: Rule
    services:
      - name: {{ $.Values.name }}
        namespace: {{ .Values.metadata.namespace }}
        port: {{ .Values.service.port }}

