apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  routes:
  - match: Host(`swapp.devserver.ir`)
    kind: Rule
    services:
      - name: {{ $.Values.name }}
        namespace: {{ .Values.metadata.namespace }}
        port: {{ .Values.service.port }}

