name: web2
replica: 1
image:
  name: shirzadi/simple-web-app
  tag: latest
metadata:
  namespace: swapp2
env:
  - name: background
    value: "purple"
  - name: color
    value: "yellow"
  - name: text
    value: "Hello world"
service:
  port: 8000
  type: ClusterIP
ingress:
  host: "swapp2.devserver.ir"